// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Tea_app = require("rescript-tea/src/tea_app.bs.js");
var Tea_html = require("rescript-tea/src/tea_html.bs.js");
var Caml_array = require("rescript/lib/js/caml_array.js");

function init(param) {
  return [
          [
            0,
            0,
            0
          ],
          [
            0,
            0,
            0
          ],
          [
            0,
            0,
            0
          ]
        ];
}

function update(model, msg) {
  Caml_array.set(Caml_array.get(model, msg._0), msg._1, 1);
  return model;
}

function viewButton(title, msg) {
  return Tea_html.button(undefined, undefined, {
              hd: Tea_html.Events.onClick(msg),
              tl: /* [] */0
            }, {
              hd: Tea_html.text(title),
              tl: /* [] */0
            });
}

function view(model) {
  return Tea_html.div(undefined, undefined, {
              hd: Tea_html.Attributes.$$class("wrapper"),
              tl: /* [] */0
            }, {
              hd: Tea_html.div(undefined, undefined, {
                    hd: Tea_html.Attributes.$$class("field"),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.div(undefined, undefined, {
                          hd: Tea_html.Attributes.$$class("row"),
                          tl: /* [] */0
                        }, {
                          hd: Tea_html.div(undefined, undefined, {
                                hd: Tea_html.Attributes.$$class("left_upper"),
                                tl: /* [] */0
                              }, /* [] */0),
                          tl: {
                            hd: Tea_html.div(undefined, undefined, {
                                  hd: Tea_html.Attributes.$$class("center_upper"),
                                  tl: /* [] */0
                                }, /* [] */0),
                            tl: {
                              hd: Tea_html.div(undefined, undefined, {
                                    hd: Tea_html.Attributes.$$class("right_upper"),
                                    tl: /* [] */0
                                  }, /* [] */0),
                              tl: /* [] */0
                            }
                          }
                        }),
                    tl: {
                      hd: Tea_html.div(undefined, undefined, {
                            hd: Tea_html.Attributes.$$class("row"),
                            tl: /* [] */0
                          }, {
                            hd: Tea_html.div(undefined, undefined, {
                                  hd: Tea_html.Attributes.$$class("left_middle"),
                                  tl: /* [] */0
                                }, /* [] */0),
                            tl: {
                              hd: Tea_html.div(undefined, undefined, {
                                    hd: Tea_html.Attributes.$$class("center_middle"),
                                    tl: /* [] */0
                                  }, {
                                    hd: Tea_html.div(undefined, undefined, {
                                          hd: Tea_html.Attributes.$$class("circle"),
                                          tl: /* [] */0
                                        }, {
                                          hd: Tea_html.text("x"),
                                          tl: /* [] */0
                                        }),
                                    tl: /* [] */0
                                  }),
                              tl: {
                                hd: Tea_html.div(undefined, undefined, {
                                      hd: Tea_html.Attributes.$$class("right_middle"),
                                      tl: /* [] */0
                                    }, /* [] */0),
                                tl: /* [] */0
                              }
                            }
                          }),
                      tl: {
                        hd: Tea_html.div(undefined, undefined, {
                              hd: Tea_html.Attributes.$$class("row"),
                              tl: /* [] */0
                            }, {
                              hd: Tea_html.div(undefined, undefined, {
                                    hd: Tea_html.Attributes.$$class("left_lower"),
                                    tl: /* [] */0
                                  }, /* [] */0),
                              tl: {
                                hd: Tea_html.div(undefined, undefined, {
                                      hd: Tea_html.Attributes.$$class("center_lower"),
                                      tl: /* [] */0
                                    }, /* [] */0),
                                tl: {
                                  hd: Tea_html.div(undefined, undefined, {
                                        hd: Tea_html.Attributes.$$class("right_lower"),
                                        tl: /* [] */0
                                      }, /* [] */0),
                                  tl: /* [] */0
                                }
                              }
                            }),
                        tl: /* [] */0
                      }
                    }
                  }),
              tl: /* [] */0
            });
}

var partial_arg_model = init(undefined);

var partial_arg = {
  model: partial_arg_model,
  update: update,
  view: view
};

function main(param, param$1) {
  return Tea_app.beginnerProgram(partial_arg, param, param$1);
}

exports.init = init;
exports.update = update;
exports.viewButton = viewButton;
exports.view = view;
exports.main = main;
/* partial_arg Not a pure module */
